<?php

namespace Database\Factories;

use App\Enums\ParkingStatus;
use App\Models\ParkingTicket;
use App\Models\User;
use App\Models\VehicleType;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ParkingTicket>
 */
class ParkingTicketFactory extends Factory
{
    protected $model = ParkingTicket::class;

    /**
     * Configure the factory.
     */
    public function configure(): static
    {
        return $this->afterMaking(function (ParkingTicket $ticket) {
            // Ensure ticket_number is set based on check_in date
            if (empty($ticket->ticket_number)) {
                $checkInDate = $ticket->check_in instanceof Carbon
                    ? $ticket->check_in
                    : Carbon::parse($ticket->check_in);
                $ticket->ticket_number = ParkingTicket::generateTicketNumber($checkInDate);
            }
        });
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $checkIn = $this->faker->dateTimeBetween('-7 days', 'now');

        return [
            // ticket_number is auto-generated by the model's boot method
            'vehicle_no' => $this->generateNepaliVehicleNumber(),
            'vehicle_type_id' => VehicleType::factory(),
            'phone_number' => $this->generateNepaliPhoneNumber(),
            'check_in' => $checkIn,
            'check_out' => null,
            'total_price' => null,
            'status' => ParkingStatus::Parked,
            'notes' => $this->faker->optional(0.3)->sentence(),
            'checked_in_by' => User::factory(),
            'checked_out_by' => null,
        ];
    }

    /**
     * Generate a Nepali vehicle number.
     */
    protected function generateNepaliVehicleNumber(): string
    {
        $provinces = ['Ba', 'Ga', 'Ko', 'Lu', 'Dh', 'Ja', 'Bh'];
        $province = $this->faker->randomElement($provinces);
        $number = $this->faker->randomNumber(1, true);
        $series = $this->faker->randomElement(['Pa', 'Cha', 'Ja', 'Kha']);
        $digits = $this->faker->randomNumber(4, true);

        return "{$province} {$number} {$series} {$digits}";
    }

    /**
     * Generate a valid Nepali phone number.
     */
    protected function generateNepaliPhoneNumber(): string
    {
        $prefixes = ['97', '98', '96'];
        $prefix = $this->faker->randomElement($prefixes);

        return $prefix.$this->faker->numerify('########');
    }

    /**
     * Indicate that the vehicle has exited.
     */
    public function exited(): static
    {
        return $this->state(function (array $attributes) {
            $checkIn = $attributes['check_in'] ?? now()->subHours(rand(1, 8));
            $checkOut = $this->faker->dateTimeBetween($checkIn, 'now');

            return [
                'check_out' => $checkOut,
                'status' => ParkingStatus::Exited,
                'total_price' => $this->faker->randomFloat(2, 20, 500),
                'checked_out_by' => User::factory(),
            ];
        });
    }

    /**
     * Indicate that the vehicle is currently parked.
     */
    public function parked(): static
    {
        return $this->state(fn (array $attributes) => [
            'check_out' => null,
            'total_price' => null,
            'status' => ParkingStatus::Parked,
            'checked_out_by' => null,
        ]);
    }

    /**
     * Create a ticket for today.
     */
    public function today(): static
    {
        return $this->state(fn (array $attributes) => [
            'check_in' => $this->faker->dateTimeBetween('today', 'now'),
        ]);
    }
}
